Controllers/CustomerController.cs
using Hakuna.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
namespace Hakuna.Controllers
{
    public class CustomerController : Controller
    {
        private readonly AppDbContext _dbcontext;
        public CustomerController(AppDbContext injectedContext)
        {
            _dbcontext = injectedContext;
        }
        public void  Success(string message)
        {
            ViewData["success"]=true;
            ViewData["message"] = message;
        }

        public void Fail(string message)
        {
            ViewData["fail"] = true;
            ViewData["message"] = message;
        }

        public IActionResult Add()
        {
            ICollection<Membership> memberships = _dbcontext.Membershiptypes.ToList();
            ViewBag.Members = new SelectList(memberships, "Id", "Title");
            return View(new Customer());
        }
        static bool IsValid(Customer customer)
        {
            if (customer.Name == null)
            {return false;}
            if (customer.LastName == null)
            {return false;}
            if (customer.Age < 16)
            {return false;}
            if (customer.MembershipId == null)
            {return false;}
            return true;
        }
        [HttpPost]
        public IActionResult Add(Customer customer)
        {
            if (!IsValid(customer)){
                Fail("Can't Add Customer, check your input");
            }else{
                _dbcontext.Add(customer);
                _dbcontext.SaveChanges();
                Success("Added Customer successfully!");
            }
            return ListAll();
        }
        public IActionResult ListAll()
        {
            
            var customers = _dbcontext.Customers.ToList();
            
            return View("ListAll",customers);
        }

        public IActionResult Index()
        {
            return ListAll();
        }
        public IActionResult Details(Guid id)
        {
            var customer = _dbcontext.Customers
                .Include(c => c.Membershiptype)
                .FirstOrDefault(c => c.Id == id);
            if (customer == null)
            {
                return View(nameof(ListAll));
            }
            return View(customer);
        }

        public IActionResult Delete(Guid id)
        {
            var customer = _dbcontext.Customers.Find(id);
            if (customer == null)
            {
                Fail("Couldn't Delete Customer. Could be Already Deleted!");
            }
            else
            {
                _dbcontext.Customers.Remove(customer);
                _dbcontext.SaveChanges();
                Success("Customer Deleted Successfully");
            }
            
            return ListAll();
        }
        
        public IActionResult Edit(Guid id)
        {
            ICollection<Membership> memberships = _dbcontext.Membershiptypes.ToList();
            ViewBag.Members = new SelectList(memberships, "Id", "Title");
            var customer = _dbcontext.Customers.FirstOrDefault(c => c.Id==id);
            if (customer == null)
                return ListAll();
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            if (!IsValid(customer))
            {
                Fail("Cannot update customer due to input");
                return Edit(customer.Id);
            }
            Customer? existingCustomer = _dbcontext.Customers.Find(customer.Id);
            
            if (existingCustomer == null)
            {
                return NotFound();
            }

            // Update the properties of the existing movie with the values from the form
            _dbcontext.Entry(existingCustomer).CurrentValues.SetValues(customer);

            // Save changes to the database
            _dbcontext.SaveChanges();
            Success("Customer updated Successfully");
            return ListAll();
        }
        [Route("Customer/BuyMovie/{customerId}")]
        public IActionResult BuyMovie(Guid customerId)
        {
            var movies = _dbcontext.Movies.ToList();
            ViewBag.CustomerId = customerId;
            return View(movies);
        }
        [Route("Customer/BuyMovie/{customerId}/{movieId}")]
        public IActionResult BuyMovie(Guid customerId, Guid movieId)
        {
            var customer = _dbcontext.Customers
                .Include(customer1 => customer1.Movies)
                .FirstOrDefault(custo => custo.Id == customerId);
            var movie = _dbcontext.Movies.Find(movieId);
            if (customer == null)
            {
                Fail("Customer not found");
                return ListAll();
            }

            if (movie == null)
            {
                Fail("Movie not found");
                return ListAll();
            }
            if (!customer.Movies.Contains(movie))
            {
                customer.Movies.Add(movie);
                _dbcontext.SaveChanges();
                Success("Associated movie with client successfully!");
            }
            else
            {
                Fail("Customer already bought this movie");
            }

            return SeeMovies(customerId);
        }

        public IActionResult SeeMovies(Guid customerId)
        {
            var customer = _dbcontext.Customers
                .Include(c => c.Movies)
                .FirstOrDefault(c => c.Id == customerId);
            if (customer == null)
                return ListAll();
            return View("SeeMovies",customer);
        }
    }
    
}

Controllers/GenreController.cs
using System.ComponentModel.DataAnnotations;
using Hakuna.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
namespace Hakuna.Controllers
{
    public class GenreController : Controller
    {
        private readonly AppDbContext _context;
        public GenreController(AppDbContext context)
        {
            this._context = context;
        }
        public void  Success(string message)
        {
            ViewData["success"]=true;
            ViewData["message"] = message;
        }

        public void Fail(string message)
        {
            ViewData["fail"]=true;
            ViewData["message"] = message;
        }
        public IActionResult Add()
        {
            Genre genre = new Genre();
            return View("Add",genre);
        }
        [HttpPost]
        public IActionResult Add( Genre genre)
        {
            if (genre.Name != null)
            {
                _context.Add(genre);
                _context.SaveChanges();
                Success("Added Genre Successfully!");
            }
            else
            {
                Fail("Couldn't add Genre, please check your input!");
            }

            return Add();
        }
        public IActionResult Index(){
            return RedirectToAction("ListAll","Movie");
        }
         public IActionResult ListAll(){
            List<Genre> genres = _context.Genres.ToList();
            _context.SaveChanges();
            return View(genres);
        } 
        /* public IActionResult Details(Guid id){
           
            var movies = context.Movies.ToList();            
            foreach (var el in movies){
                if (el.Id==id){
                    return View(el);
                }
            }
            return NotFound();
            
        }*/ 
        /* public IActionResult Delete(Guid id){
            var movie = context.Movies.Find(id);
            if (movie is not null)
            {
                context.Movies.Remove(movie);
                context.SaveChanges();
            }
            return RedirectToAction("ListAll");
            
        } */ 
    }
}

Controllers/MembershipController.cs
using Hakuna.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Hakuna.Controllers
{
    
public class MembershipController : Controller
{
    public void  Success(string message)
    {
        ViewData["success"]=true;
        ViewData["message"] = message;
    }

    public void Fail(string message)
    {
        ViewData["fail"]=true;
        ViewData["message"] = message;
    }
    private readonly AppDbContext db;

    public MembershipController(AppDbContext _context)
    {
        db = _context;
    }
    public IActionResult Index()
    {
        return RedirectToAction("List");
    }

    public IActionResult Add()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Add(Membership membership)
    {
        if (membership.DurationInMonth <= 0
            || membership.DiscountRate < 0
            || membership.Title == null
            || membership.SignUpFee < 0)
        {
            Fail("Membership cannot be Added due to input input!");
        }
        try
        {
            db.Add(membership);
            db.SaveChanges();
        }
        catch (Exception)
        {
            Fail("Membership cannot be Added due to database problem!");
        }
        Success("Membership has been added successfully!");
        return Add();
    }
    public IActionResult List()
    {
        List<Membership> membershiptypes = db.Membershiptypes.ToList();
        
        return View(membershiptypes);
    }
    public IActionResult Details(Guid id)
    {
        var membership = db.Membershiptypes.Find(id);
        if (membership == null)
            return List();
        return View(membership);
    }

}
}

Views/Shared/_AddForm.cshtml
@{
    Layout = "_Layout.cshtml";
}
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    var controllerName = ViewContext.RouteData.Values["controller"] as string;
}
@Html.Partial("_SuccessFlash")
@Html.Partial("_FailFlash")
<h1>@ViewBag.Title</h1>

<hr>
<form method = "post" asp-controller="@controllerName" enctype = "multipart/form-data"  asp-action="Add">
    <div class="card"> 
        <div class="card-header">
            <h3>@ViewBag.AddHeadline</h3>
        </div>
        <div class="card-body">
            @RenderBody()
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>


    </div>
</form>

Views/Shared/_DetailsLayout.cshtml
@{
    Layout = "_Layout.cshtml";
    var controllerName = ViewContext.RouteData.Values["controller"] as string;
}
@Html.Partial("_SuccessFlash")
@Html.Partial("_FailFlash")
<h1>@ViewBag.Title</h1>
<hr>
    
    <div class="card col-md-6 col-sm-12"> 
        <div class="card-body">
            @RenderBody()
        </div>
        <div class="card-footer">
            <form method="post" asp-controller="@controllerName" asp-action="Delete" asp-route-id="@Model.Id">
                <button type="submit" class="btn btn-danger me-3">
                    Delete
                </button>
                <a href="@Url.Action("Edit", controllerName,new{id=Model.Id})" class="btn btn-primary btn-info">Edit</a>
            </form>
            

        </div>
    </div>

Views/Shared/_EditLayout.cshtml
@{ /* 
 needs @ViewBag.EditHeadline
 ***/
    Layout = "_Layout.cshtml";
}
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    var controllerName = ViewContext.RouteData.Values["controller"] as string;
}
@Html.Partial("_SuccessFlash")
@Html.Partial("_FailFlash")
<h1>@ViewBag.Title</h1>

<hr>
<form method = "post" asp-controller="@controllerName" enctype = "multipart/form-data"  asp-action="Edit">
    <div class="card"> 
        <div class="card-header">
            <h3>@ViewBag.EditHeadline</h3>
        </div>
        <div class="card-body">
            @RenderBody()
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>


    </div>
</form>

Views/Shared/_FailFlash.cshtml
@{
    bool fail = false;
    if (ViewData.ContainsKey("fail"))
    {
        fail = (bool)(ViewData["fail"] ?? false);
    }
}
@if(fail)
{
    <style>
        #fail-alert{
            position: fixed;
            top: 20px;
            left: 50%;
            transform: translateX(-50%);
            z-index: 1000;
            transition: opacity 1s ease-in-out;
        }
        #fail-alert.fade{
            opacity: 0;
        }
        
    </style>
    <div id="fail-alert" class="alert alert-danger">
        @ViewData["message"]
    </div>
    {ViewData["fail"]=false;}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC Movie </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hakuna.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    @Html.Partial("_NavBar")
        
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    
</body>
<footer class="border-top footer layout-footer text-muted" style="color:black; bottom:unset;">
    <div class="container">
        &copy; 2023 - Hakuna - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>
<script>
    document.addEventListener("DOMContentLoaded", function () {
    let successAlert = document.getElementById("fail-alert");
    setTimeout(function(){
         successAlert.style.cssText = "opacity:0;";
    },1000)
    
});
</script>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hakuna</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="ListAll">Movies</a></li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ListAll">Customers</a></li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="ListAll">Genres</a></li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Membership" asp-action="List">Membership</a></li>
                    </ul>
                </div>
            </div>
        </nav>

Views/Shared/_SuccessFlash.cshtml
@{
    bool success = false;
    if (ViewData.ContainsKey("success"))
    {
        success = (bool)(ViewData["success"] ?? false);
    }
}
@if(success)
{
    <style>
        #success-alert{
            position: fixed;
            top: 20px;
            left: 50%;
            transform: translateX(-50%);
            z-index: 1000;
            transition: opacity 1s ease-in-out;
        }
        .fade{
            opacity: 0;
        }
        
    </style>
    <div id="success-alert" class="alert alert-success">
        @ViewData["message"]
    </div>
    {ViewData["success"]=false;}
    <script >
    document.addEventListener("DOMContentLoaded", function () {
    var successAlert = document.getElementById("success-alert");
    setTimeout(function(){
         if (successAlert !== null){
             console.log(successAlert);
         //    successAlert.style.opacity="0";
         successAlert.classList.add("fade")
         successAlert.style.opacity="0";
         successAlert.style.cssText=" opacity: 0 ; ";
         }
    },1000)
    
    });
</script>
}